
            <nav id="sidebar" role="navigation" data-step="2" data-intro="Template has &lt;b&gt;many navigation styles&lt;/b&gt;"
                data-position="right" class="navbar-default navbar-static-side">
            <div class="sidebar-collapse menu-scroll">
                <ul id="side-menu" class="nav">
                    
                     <div class="clearfix"></div>
                    <li class=""><a href="creardeporte"><i class="fa fa-tachometer fa-fw">
                        <div class="icon-bg bg-orange"></div>
                    </i><span class="menu-title">Deportes</span></a></li>
                    <li><a href="<?php echo $this->url('secciondeporte')?>"><i class="fa fa-desktop fa-fw">
                        <div class="icon-bg bg-pink"></div>
                    </i><span class="menu-title">Secciones</span></a>
                       
                    </li>
                    <li><a href="<?php echo $this->url('subseccion')?>"><i class="fa fa-send-o fa-fw">
                        <div class="icon-bg bg-green"></div>
                    </i><span class="menu-title">Sub-secciones</span></a>
                       
                    </li>
                    <li><a href="../../eventos"><i class="fa fa-edit fa-fw">
                        <div class="icon-bg bg-violet"></div>
                    </i><span class="menu-title">Crear Evento</span></a>
                      
                    </li>
                    <li><a href="../../vendedores"><i class="fa fa-th-list fa-fw">
                        <div class="icon-bg bg-blue"></div>
                    </i><span class="menu-title">Crear Vendedores</span></a>
                          
                    </li>
                                        
                </ul>
            </div>
        </nav>
            
    <!--div>
        
        <div id="wrapper">
            <nav id="sidebar" role="navigation" data-step="2" data-intro="Template has &lt;b&gt;many navigation styles&lt;/b&gt;"
                data-position="right" class="navbar-default navbar-static-side">
            <div class="sidebar-collapse menu-scroll">
                <ul id="side-menu" class="nav">
                    
                     <div class="clearfix"></div>
                    <li class="active"><a href="dashboard.html"><i class="fa fa-tachometer fa-fw">
                        <div class="icon-bg bg-orange"></div>
                    </i><span class="menu-title">Deportes</span></a></li>
                    <li><a href="creardeporte"><i class="fa fa-desktop fa-fw">
                        <div class="icon-bg bg-pink"></div>
                    </i><span class="menu-title">Secciones</span></a>
                       
                    </li>
                    <li><a href="../../secciondeporte"><i class="fa fa-send-o fa-fw">
                        <div class="icon-bg bg-green"></div>
                    </i><span class="menu-title">Sub-secciones</span></a>
                       
                    </li>
                    <li><a href="../../subseccion"><i class="fa fa-edit fa-fw">
                        <div class="icon-bg bg-violet"></div>
                    </i><span class="menu-title">Crear Evento</span></a>
                      
                    </li>
                    <li><a href="../../eventos"><i class="fa fa-th-list fa-fw">
                        <div class="icon-bg bg-blue"></div>
                    </i><span class="menu-title">Crear Vendedores</span></a>
                          
                    </li>
                                        
                </ul>
            </div>
        </nav>
            </div>
        </div-->