
<div class="col-lg-12">
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-green">
                <div class="panel-heading">
                    Editar Deportes</div>
                <div class="panel-body pan">
                    <form action="" method="post" id="frmdeporte" name="frmdeporte">
                        <div class="form-body pal">
                            <div class="row">
                                <div class="form-group">
                                    <label for="inputName" class="control-label">Nombre deporte</label>
                                    <div class="input-icon right">
                                        <i class="fa fa-user"></i>
                                        <input type="text" class="form-control" id="deporte" name="deporte" placeholder="Nombre deporte" value="<?php echo $this->deporte['nombre']?>">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-actions text-right pal">
                            <input type="submit" class="btn btn-primary" name="btnguardar" id="btnguardar" value="Guardar">
                        </div>
                        <input type="hidden" name="iddeporte" id="iddeporte" value="<?php echo $this->deporte['id']?>"/>
                        </form>
                </div>
            </div>
        </div>
    </div>
</div>